to_do_list/urls.py
from django.urls import path

from to_do_list.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCompleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("task-create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "task-update/<int:pk>/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task-delete/<int:pk>/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "task-complete/<int:pk>/",
        TaskCompleteView.as_view(),
        name="task-complete"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tag-create/", TagCreateView.as_view(), name="tag-create"),
    path("tag-update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tag-delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "to_do_list"

to_do_practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("to_do_list.urls", namespace="to_do_list")),
]

to_do_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

to_do_list/forms.py
from django import forms

from to_do_list.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            'deadline': forms.DateInput(attrs={'type': 'date'})
        }

to_do_list/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic, View

from to_do_list.forms import TaskForm
from to_do_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    ordering = ["-is_completed", "-created_at"]


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("to_do_list:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("to_do_list:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("to_do_list:task-list")


class TaskCompleteView(View):
    @staticmethod
    def post(request, pk) -> HttpResponseRedirect:
        task = Task.objects.get(pk=pk)

        task.is_completed = not task.is_completed

        task.save()

        return HttpResponseRedirect(
            reverse("to_do_list:task-list")
        )


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("to_do_list:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
        crossorigin="anonymous">

  <title>
    {% block title %}{% endblock %}
  </title>

</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">

        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}

      </div>
      <div class="col-sm-10 ">

        {% block content %}{% endblock %}

      </div>
    </div>
  </div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group mt-3">
  <li class="list-group-item"><a href="{% url "to_do_list:task-list" %}">Home</a></li>
  <li class="list-group-item"><a href="{% url "to_do_list:tag-list" %}">Tags</a></li>
</ul>

templates/to_do_list/tag_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Confirm deletion{% endblock %}

{% block content %}
  <div class="mt3">
    <h1>Are you sure you want to delete this tag?</h1>
    <h3 class="m-2">{{ tag.name }}</h3>
  </div>
  <form action="#" method="post">
    {{ form|crispy }}
    {% csrf_token %}

    <div class="m-2 mt-4">
      <input type="submit" value="Yes, delete" class="btn btn-danger">
      <a href="{% url "to_do_list:task-list" %}" class="btn btn-primary">No, go back</a>
    </div>

  </form>
{% endblock %}

templates/to_do_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Tag{% endblock %}

{% block content %}
  {% if task %}
    <h1 class="mt-3">Update tag</h1>
    {% else %}
    <h1 class="mt-3">Create new tag</h1>
  {% endif %}

  <form action="#" class="w-50" method="post">
    {{ form|crispy }}
    {% csrf_token %}

    {% if tag %}
      <input type="submit" value="Update" class="btn btn-primary">
      {% else %}
      <input type="submit" value="Create" class="btn btn-primary">
    {% endif %}
  </form>
{% endblock %}

templates/to_do_list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="mt-3">
    <h1>Tag list <a href="{% url "to_do_list:tag-create" %}"
    class="btn btn-success float-right">Add tag</a></h1>
  </div>


  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>

    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a href="{% url "to_do_list:tag-update" pk=tag.pk %}">update</a></td>
        <td><a href="{% url "to_do_list:tag-delete" pk=tag.pk %}">delete</a></td>
      </tr>
    {% endfor %}


  </table>

{% endblock %}

templates/to_do_list/task_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Confirm deletion{% endblock %}

{% block content %}
  <div class="mt3">
    <h1>Are you sure you want to delete this task?</h1>
    <h3>{{ task.content }}</h3>
  </div>
  <form action="#" method="post">
    {{ form|crispy }}
    {% csrf_token %}

    <div class="m-2 mt-4">
      <input type="submit" value="Yes, delete" class="btn btn-danger">
      <a href="{% url "to_do_list:task-list" %}" class="btn btn-primary">No, go back</a>
    </div>
  </form>
{% endblock %}

templates/to_do_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Task{% endblock %}

{% block content %}
  {% if task %}
    <h1 class="mt-3">Update task</h1>
    {% else %}
    <h1 class="mt-3">Create new task</h1>
  {% endif %}

  <form action="#" class="w-50" method="post">
    {{ form|crispy }}
    {% csrf_token %}

    {% if task %}
      <input type="submit" value="Update" class="btn btn-primary">
      {% else %}
      <input type="submit" value="Create" class="btn btn-primary">
    {% endif %}
  </form>
{% endblock %}

templates/to_do_list/task_list.html
{% extends "base.html" %}

{% block content %}
  <div class="mt-3">
    <h1>To Do list <a href="{% url "to_do_list:task-create" %}"
    class="btn btn-success float-right">Add task</a></h1>
  </div>

  {% for task in task_list %}
    <div class="m-3 border-bottom">
      <h3>
        {{ task.content }}
      {% if task.is_completed %}
        <span class="text-success">done</span>
        <form action="{% url "to_do_list:task-complete" pk=task.pk %}" method="post" class="float-right">
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary">Undo</button>
        </form>
        {% else %}
        <span class="text-danger">not done</span>
        <form action="{% url "to_do_list:task-complete" pk=task.pk %}" method="post" class="float-right">
          {% csrf_token %}
          <button type="submit" class="btn btn-success">Complete</button>
        </form>
      {% endif %}

      </h3>

      {% if task.deadline %}
        <p>Deadline: {{ task.deadline }}</p>
      {% endif %}
      <p class="text-muted">Created at: {{ task.created_at }}</p>
      <p>Tags: {% for tag in task.tags.all %}<span class="text-white bg-dark p-1">{{ tag.name }} </span>{% endfor %}</p>
      <p>
        <a href="{% url "to_do_list:task-update" pk=task.pk %}"
        class="btn btn-link">update</a>
        <a href="{% url "to_do_list:task-delete" pk=task.pk %}"
        class="btn btn-link">delete</a>
      </p>
      <br>
    </div>
  {% endfor %}

{% endblock %}